apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudl-client-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudl-client
    spec:
      containers:
        - name: cloudl-client
          image: sajjadhz/cloudl-client:v1
          ports:
            - containerPort: 80
              name: http-port
          env:
            - name: API_HOST
              valueFrom:
                configMapKeyRef:
                  key: API_HOST
                  name: cloudl-configmap
                  optional: false
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  key: API_PORT
                  name: cloudl-configmap
                  optional: false
            - name: CLOUDL_SERVER
              valueFrom:
                configMapKeyRef:
                  key: CLOUDL_SERVER
                  name: cloudl-configmap
                  optional: false
  selector:
    matchLabels:
      app: cloudl-client
---
apiVersion: v1
kind: Service
metadata:
  name: cloudl-client-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-port
      nodePort: 30007
  selector:
    app: cloudl-client
  type: NodePort